// <auto-generated />
using System;
using AstroTogether.BackEnd.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstroTogether.BackEnd.Migrations
{
    [DbContext(typeof(AstroTogetherContext))]
    [Migration("20230303030452_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Actor", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Initial")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ActorId");

                    b.HasIndex(new[] { "Email" }, "IX_Actor_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "LastName", "FirstName", "Initial" }, "IX_Actor_LastName_FirstName_Initial");

                    b.ToTable("Actor", (string)null);
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Attendee", b =>
                {
                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AttendeeId");

                    b.HasIndex("MemberId");

                    b.HasIndex(new[] { "MeetId", "MemberId" }, "IX_Attendee_MeetId_MemberId")
                        .IsUnique();

                    b.ToTable("Attendee", (string)null);
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Club", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ClubId");

                    b.HasIndex(new[] { "Name" }, "IX_Club_Name")
                        .IsUnique();

                    b.ToTable("Club", (string)null);
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Crew", b =>
                {
                    b.Property<Guid>("CrewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CrewId");

                    b.HasIndex("AdminId");

                    b.HasIndex(new[] { "ClubId", "Name" }, "IX_Crew_ClubId_Name");

                    b.ToTable("Crew", (string)null);
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Meet", b =>
                {
                    b.Property<Guid>("MeetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MeetId");

                    b.HasIndex("CrewId");

                    b.HasIndex(new[] { "SiteId", "CrewId", "Date" }, "IX_Meet_SiteId_CrewId_Date")
                        .IsUnique();

                    b.ToTable("Meet", (string)null);
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.HasIndex("ActorId");

                    b.HasIndex(new[] { "ClubId", "ActorId" }, "IX_Member_ClubId_ActorId")
                        .IsUnique();

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Site", b =>
                {
                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Blurb")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SiteId");

                    b.HasIndex(new[] { "ClubId", "Name" }, "IX_Site_ClubId_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "IX_Site_Name")
                        .IsUnique();

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Attendee", b =>
                {
                    b.HasOne("AstroTogether.BackEnd.DB.Meet", "Meet")
                        .WithMany("Attendees")
                        .HasForeignKey("MeetId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendee_Meet");

                    b.HasOne("AstroTogether.BackEnd.DB.Member", "Member")
                        .WithMany("Attendees")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendee_Member");

                    b.Navigation("Meet");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Crew", b =>
                {
                    b.HasOne("AstroTogether.BackEnd.DB.Member", "Admin")
                        .WithMany("Crews")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK_Crew_Member");

                    b.HasOne("AstroTogether.BackEnd.DB.Club", "Club")
                        .WithMany("Crews")
                        .HasForeignKey("ClubId")
                        .IsRequired()
                        .HasConstraintName("FK_Crew_Club");

                    b.OwnsOne("AstroTogether.BackEnd.DB.CrewPolicy", "Policy", b1 =>
                        {
                            b1.Property<Guid>("CrewId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AutoAttend")
                                .HasColumnType("bit");

                            b1.HasKey("CrewId");

                            b1.ToTable("Crew");

                            b1.ToJson("Policy");

                            b1.WithOwner()
                                .HasForeignKey("CrewId");
                        });

                    b.Navigation("Admin");

                    b.Navigation("Club");

                    b.Navigation("Policy")
                        .IsRequired();
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Meet", b =>
                {
                    b.HasOne("AstroTogether.BackEnd.DB.Crew", "Crew")
                        .WithMany("Meets")
                        .HasForeignKey("CrewId")
                        .IsRequired()
                        .HasConstraintName("FK_Meet_Crew");

                    b.HasOne("AstroTogether.BackEnd.DB.Site", "Site")
                        .WithMany("Meets")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK_Meet_Site");

                    b.OwnsOne("AstroTogether.BackEnd.DB.MeetDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("MeetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("StartOn")
                                .HasColumnType("datetime2");

                            b1.HasKey("MeetId");

                            b1.ToTable("Meet");

                            b1.ToJson("Details");

                            b1.WithOwner()
                                .HasForeignKey("MeetId");
                        });

                    b.Navigation("Crew");

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Member", b =>
                {
                    b.HasOne("AstroTogether.BackEnd.DB.Actor", "Actor")
                        .WithMany("Members")
                        .HasForeignKey("ActorId")
                        .IsRequired()
                        .HasConstraintName("FK_Member_Actor");

                    b.HasOne("AstroTogether.BackEnd.DB.Club", "Club")
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .IsRequired()
                        .HasConstraintName("FK_Member_Club");

                    b.Navigation("Actor");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Site", b =>
                {
                    b.HasOne("AstroTogether.BackEnd.DB.Club", "Club")
                        .WithMany("Sites")
                        .HasForeignKey("ClubId")
                        .IsRequired()
                        .HasConstraintName("FK_Site_Club");

                    b.OwnsOne("AstroTogether.BackEnd.DB.SiteDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("SiteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("SiteId");

                            b1.ToTable("Site");

                            b1.ToJson("Details");

                            b1.WithOwner()
                                .HasForeignKey("SiteId");
                        });

                    b.Navigation("Club");

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Actor", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Club", b =>
                {
                    b.Navigation("Crews");

                    b.Navigation("Members");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Crew", b =>
                {
                    b.Navigation("Meets");
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Meet", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Member", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Crews");
                });

            modelBuilder.Entity("AstroTogether.BackEnd.DB.Site", b =>
                {
                    b.Navigation("Meets");
                });
#pragma warning restore 612, 618
        }
    }
}
